---
version: '3'
services:
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mimir_dev
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - 'redis-data:/data'
  proxy:
    build:
      context: ./proxy
    ports:
      - '80:80'
      - '443:443'
volumes:
  postgres:
    driver: local
  redis-data:
    driver: local
